CREATE TABLE `PALABRAS` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lema` varchar(35) COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `PALABRAS_UN` (`lema`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `CATEGORIAS` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tipo_categoria` char(1) COLLATE utf8mb4_bin NOT NULL,
  `tipo_categoria_entero` varchar(35) COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `TIPOS_PROPIEDADES` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tipo_propiedad` char(1) COLLATE utf8mb4_bin NOT NULL,
  `tipo_propiedad_entero` varchar(30) COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `TIPOS_PROPIEDADES_UN` (`tipo_propiedad`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `SENTIDOS` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_palabra` int(11) NOT NULL,
  `id_raiz` int(11) DEFAULT NULL,
  `sentido` text COLLATE utf8mb4_bin,
  PRIMARY KEY (`id`),
  KEY `SENTIDOS_FK` (`id_palabra`),
  KEY `SENTIDOS_FK_1` (`id_raiz`),
  CONSTRAINT `SENTIDOS_FK` FOREIGN KEY (`id_palabra`) REFERENCES `PALABRAS` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `SENTIDOS_FK_1` FOREIGN KEY (`id_raiz`) REFERENCES `PALABRAS` (`id`) ON DELETE SET NULL ON UPDATE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `CARACTERISTICAS` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_sentido` int(11) NOT NULL,
  `id_categoria` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CARACTERISTICAS_FK` (`id_sentido`),
  KEY `CARACTERISTICAS_FK_1` (`id_categoria`),
  CONSTRAINT `CARACTERISTICAS_FK` FOREIGN KEY (`id_sentido`) REFERENCES `SENTIDOS` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CARACTERISTICAS_FK_1` FOREIGN KEY (`id_categoria`) REFERENCES `CATEGORIAS` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `PROPIEDADES` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_tipo_propiedad` int(11) NOT NULL,
  `valor` varchar(30) COLLATE utf8mb4_bin NOT NULL,
  `id_caracteristicas` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `PROPIEDADES_TIPO` (`id_tipo_propiedad`),
  KEY `PROPIEDADES_SENTIDO` (`id_caracteristicas`),
  CONSTRAINT `PROPIEDADES_SENTIDO` FOREIGN KEY (`id_caracteristicas`) REFERENCES `CARACTERISTICAS` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `PROPIEDADES_TIPO` FOREIGN KEY (`id_tipo_propiedad`) REFERENCES `TIPOS_PROPIEDADES` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

